In [2]:
my_list = [1,2,3]

In [3]:
 import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr


array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#np.array()

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#np.arange() ..like a range in python

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones((1,2))

array([[1., 1.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [23]:
#np.linspace

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
#np.eye is an identity matrix

In [26]:
#it takes single argumrnts

In [27]:
np.random.rand()

0.596475183465633

In [28]:
np.random.rand(5)

array([0.16527964, 0.37266643, 0.7509121 , 0.17054184, 0.40332807])

In [37]:
 arr = np.random.rand(5,5)

In [30]:
np.random.rand(2)

array([0.27467182, 0.56999883])

In [31]:
np.random.randint(1,100)

69

In [32]:
np.random.randint(0,99)

49

In [33]:
np.random.randint(1,100,10)

array([47, 59,  8, 16, 89, 63, 78, 87, 65, 12])

In [34]:
ranrr = np.random.randint(0,50,10)

In [36]:
ranrr

array([33, 14, 48, 33, 38, 49, 41,  7, 28,  6])

In [38]:
ranrr

array([33, 14, 48, 33, 38, 49, 41,  7, 28,  6])

In [39]:
#reshape()

In [40]:
ranrr.min()

6

In [41]:
ranrr.max()

49

In [42]:
ranrr

array([33, 14, 48, 33, 38, 49, 41,  7, 28,  6])

In [43]:
ranrr.argmax()

5

In [44]:
#argmax index of the maximum value

In [45]:
ranrr.argmin()

9

In [49]:
arr = np.linspace(5,5)

In [50]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [51]:
arr.shape


(50,)

In [53]:
ar = np.random.randint(1,100,10)

In [55]:
ar

array([46, 41, 70, 18, 33, 57, 63, 18, 48, 63])

In [59]:
arr.dtype

dtype('float64')

In [60]:
from numpy.random import randint

In [61]:
randint(2,10)

3

In [62]:
import numpy as np

In [63]:
arr = np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
from numpy.random import randint

In [66]:
arr[8]

8

In [67]:
arr[1:5]

array([1, 2, 3, 4])

In [68]:
 arr[0]

0

In [69]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [70]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [71]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [72]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
arr[0:5]= 100

In [74]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [75]:
arr = np.arange(0,11)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [78]:
arr[0:6] =99

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
l = arr[0:6]

In [81]:
l [:]=99

In [82]:
l

array([99, 99, 99, 99, 99, 99])

In [89]:
ar_copy = arr.copy()

In [84]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [93]:
ar_2 = np.array([[5,10,15],[20,25,30],[35,49,90]])

ar_2

In [94]:
ar_2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 49, 90]])

In [95]:
ar_2[0][0]

5

In [96]:
ar_2[0]

array([ 5, 10, 15])

In [99]:
ar_2[1][2]

30

In [100]:
ar_2[2,1]

49

In [101]:
ar_2[2][1]

49

In [102]:
ar_2[:2,1:]

array([[10, 15],
       [25, 30]])

In [103]:
ar_2[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [104]:
arr = np.arange(1,11)

In [105]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [107]:
bool =arr >5

In [108]:
bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [110]:
arr[bool]

array([ 6,  7,  8,  9, 10])

In [111]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [112]:
# condidtional selection

In [113]:
#comparing and finding the true values

In [114]:
arr[arr<3]

array([1, 2])

In [115]:
ar_2 = np.arange(50).reshape(5,10)

In [116]:
ar_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [117]:
ar_2[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [118]:
ar_2[1:3][3:5]

array([], shape=(0, 10), dtype=int32)

In [119]:
 arr = np.arange(0,11)

In [120]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [122]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [123]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [124]:
arr/arr

C:\Users\KARTHIK\anaconda4\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [125]:
arr//arr

C:\Users\KARTHIK\anaconda4\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [126]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [127]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [128]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [129]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [130]:
1/arr

C:\Users\KARTHIK\anaconda4\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [131]:
arr**arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [132]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [133]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [134]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [136]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [137]:
arr.max()

10

In [138]:
arr.min()

0

In [139]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [140]:
np.log(arr)

C:\Users\KARTHIK\anaconda4\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [144]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [145]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [147]:
np.ones(10) *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [148]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [149]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [150]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [151]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [153]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [161]:
np.random.rand()

0.9941004760715019

In [165]:
np.random.randn(25)

array([-1.91253536,  0.51830246,  1.51174624, -0.11393412, -0.38255191,
        0.81427944, -0.76795653,  0.77252842,  0.13886402,  1.61308785,
       -0.03903708,  0.72180357, -0.60805701,  0.39832852, -0.36189733,
        0.6854151 , -0.59179318, -0.55646373,  2.4524325 ,  1.35758957,
        1.19675254,  1.76528953,  0.8205568 , -1.64636405, -0.28552191])

In [168]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [169]:
np.linspace(0.001,1,100).reshape(10,10)

array([[0.001     , 0.01109091, 0.02118182, 0.03127273, 0.04136364,
        0.05145455, 0.06154545, 0.07163636, 0.08172727, 0.09181818],
       [0.10190909, 0.112     , 0.12209091, 0.13218182, 0.14227273,
        0.15236364, 0.16245455, 0.17254545, 0.18263636, 0.19272727],
       [0.20281818, 0.21290909, 0.223     , 0.23309091, 0.24318182,
        0.25327273, 0.26336364, 0.27345455, 0.28354545, 0.29363636],
       [0.30372727, 0.31381818, 0.32390909, 0.334     , 0.34409091,
        0.35418182, 0.36427273, 0.37436364, 0.38445455, 0.39454545],
       [0.40463636, 0.41472727, 0.42481818, 0.43490909, 0.445     ,
        0.45509091, 0.46518182, 0.47527273, 0.48536364, 0.49545455],
       [0.50554545, 0.51563636, 0.52572727, 0.53581818, 0.54590909,
        0.556     , 0.56609091, 0.57618182, 0.58627273, 0.59636364],
       [0.60645455, 0.61654545, 0.62663636, 0.63672727, 0.64681818,
        0.65690909, 0.667     , 0.67709091, 0.68718182, 0.69727273],
       [0.70736364, 0.71745455, 0.7275454

In [171]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [172]:
mat = np.arange(1,26).reshape(5,5)

In [173]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [174]:
mat[2:,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [176]:
mat[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [177]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [178]:
mat[-1]

array([21, 22, 23, 24, 25])

In [179]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [180]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [181]:
np.sum(mat)

325

In [182]:
np.std(mat)

7.211102550927978

In [184]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [185]:
 # THANK YOU